theme: jekyll-theme-minimal
title: South Wales Writer, Technologist, and Presenter - Chris Lynch
description: I’m a South Wales based writer, technologist, digital marketeer, film-maker, comic book guy, hypnotist, foodie, and general nuisance.
